name: zombie_classifier
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip=19.2.3
  - bottleneck=1.2.1
  - hdf5storage=0.1.15
  - notebook=5.7.8
  - matplotlib=2.2.3
  - numpy=1.17.0
  - pandas=0.25.0
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - seaborn=0.11.2
  - six=1.12.0
  - spyder=3.3.4
  - xlrd=1.2.0
  - pip:
    - pyqt5==5.10
    - yagmail==0.11.220